### ISSUE TITLE
CHECK & REPAIR - COURT A BUZZER

### ISSUE THREAD

**Issue by sportsandgames** [CitySportsClub/Engineering#112]
Location: B3 Court A
Details: PLs. check buzzer " lahi na og tingog"

thanks

hanna

**Comment by buildingengineers** [comment]
Hello Ms. Hon,

Our maintenance personnel checked this yesterday and found out that the buzzer is unrepairable and now subject for replacement. The problem is on the coil inside of the buzzer. 

We have already informed the incharged at B3 regarding on this. We would like to recommend to your good office to buy a new buzzer.

Thanks,

Noel

**Comment by buildingengineers** [comment]
Done c/o Tech. Ricky
